CREATE TABLE IF NOT EXISTS used_ids (
    id TEXT PRIMARY KEY,
    created TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS ips (
    ip TEXT PRIMARY KEY,
    score INTEGER NOT NULL,
    description TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    email TEXT PRIMARY KEY,
    hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    totp TEXT NOT NULL,
    cipher TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS login (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    valid TEXT NOT NULL,
    browser TEXT NOT NULL
);
